"""update schema for ml integration

Revision ID: fc88e021507e
Revises: 114fa4249cce
Create Date: 2026-08-01 13:24:38.172517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc88e021507e'
down_revision: Union[str, Sequence[str], None] = '114fa4249cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'customers',
        sa.Column(
            'employment_years',
            sa.Integer(),
            server_default="0",
            nullable=False,
        )
    )
    op.add_column(
        'customers',
        sa.Column(
            'monthly_expenses',
            sa.Numeric(
                precision=15,
                scale=2
            ),
            server_default="0",
            nullable=False,
        )
    )
    op.add_column(
    'loans',
    sa.Column(
        'purpose',
        sa.String(length=100),
        server_default="Unknown",
        nullable=False,
    )
    )
    op.add_column(
        'risk_assessments',
        sa.Column(
            'customer_id',
            sa.Integer(),
            nullable=False,
        )
    )

    op.add_column(
        'risk_assessments',
        sa.Column(
            'prediction',
            sa.String(length=20),
            nullable=False,
        )
    )

    op.add_column(
        'risk_assessments',
        sa.Column(
            'probability_of_default',
            sa.Numeric(precision=5, scale=4),
            nullable=False,
        )
    )

    op.add_column(
        'risk_assessments',
        sa.Column(
            'model_version',
            sa.String(length=20),
            nullable=False,
        )
    )
    op.alter_column('risk_assessments', 'risk_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'risk_assessments', 'customers', ['customer_id'], ['id'])
    op.drop_column('risk_assessments', 'monthly_income')
    op.drop_column('risk_assessments', 'existing_emi')
    op.drop_column('risk_assessments', 'monthly_expenses')
    op.drop_column('risk_assessments', 'risk_level')
    op.drop_column('risk_assessments', 'recommendation')
    op.drop_column('risk_assessments', 'credit_score')
    op.drop_column('risk_assessments', 'employment_years')
    op.drop_column('risk_assessments', 'debt_to_income')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('debt_to_income', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('risk_assessments', sa.Column('employment_years', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('risk_assessments', sa.Column('credit_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('risk_assessments', sa.Column('recommendation', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('risk_assessments', sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('risk_assessments', sa.Column('monthly_expenses', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('risk_assessments', sa.Column('existing_emi', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('risk_assessments', sa.Column('monthly_income', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'risk_assessments', type_='foreignkey')
    op.alter_column('risk_assessments', 'risk_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('risk_assessments', 'model_version')
    op.drop_column('risk_assessments', 'probability_of_default')
    op.drop_column('risk_assessments', 'prediction')
    op.drop_column('risk_assessments', 'customer_id')
    op.add_column('loans', sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('loans', 'purpose')
    op.drop_column('customers', 'monthly_expenses')
    op.drop_column('customers', 'employment_years')
    # ### end Alembic commands ###
